name: test

on:
  push:
  pull_request:

jobs:
  vim:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Vim
        run: sudo apt-get update && sudo apt-get install -y vim

      - name: Run offline tests
        run: vim --clean --not-a-term -Nu NONE -n -es -S test/run.vim

      - name: Check help tags
        run: vim --clean --not-a-term -Nu NONE -n -es -c "helptags doc" -c qa
